db:
  url: jdbc:postgresql://localhost:5432/wallet
  username: ylab
  password: ylab
jwt:
  secret: b5f59337a612a2a7dc07328f3e7d1a04722967c7f06df20a499a7d3f91ff2a7e
  expiration: 240
  issuer: ylab
liquibase:
  schema: migration
  changelog: db/changelog/db.changelog-master.xml
  testChangelog: db/changelog/db.changelog-test.xml